spring.application.name=Task_Manager

server.port = 8084

spring.datasource.url= jdbc:postgresql://localhost:5432/Task_Manager
spring.datasource.username=postgres
spring.datasource.password=763168

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

